services:

  rabbitmq:
    container_name: ${NAMESPACE}_rabbitmq
    image: rabbitmq:${RABBITMQ_VERSION}
    env_file: .env
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  shopware:
    image: osioaliu/dockware-dev
    container_name: ${NAMESPACE}_shopware
    build:
      context: ./.docker/php
    env_file: .env
    user: ${UID_GID}
    depends_on:
      redis_session:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    ports:
      - "22:22"     # ssh
      - "80:80"     # apache2
      - "443:443"   # apache2 https
      - "8888:8888" # watch admin
      - "9998:9998" # watch storefront proxy
      - "9999:9999" # watch storefront
      - "3306:3306" # mysql port
    entrypoint: [ "fixuid", "/bin/bash", "/entrypoint.sh"]
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED}
      - PHP_VERSION=${PHP_VERSION}
    volumes:
      - db_volume:/var/lib/mysql
      - composer_cache:/var/www/.composer:delegated
      - shop_volume:/var/www/html:delegated

  redis_cache:
    container_name: ${NAMESPACE}_redis_cache
    image: redis:${REDIS_VERSION}
    sysctls:
      net.core.somaxconn: '1024'
    entrypoint: redis-server
    ports:
      - "6379:6379"
    command: [ "/etc/redis/redis.conf", "--appendonly", "yes" ]
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - redis_socket_cache:/run/redis/
      - ./.docker/redis/redis.conf:/etc/redis/redis.conf:ro

  redis_session:
    container_name: ${NAMESPACE}_redis_session
    image: redis:${REDIS_VERSION}
    sysctls:
      net.core.somaxconn: '1024'
    entrypoint: redis-server
    ports:
      - "6378:6379"
    command: [ "/etc/redis/redis.conf", "--appendonly", "yes" ]
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - redis_socket_session:/run/redis/
      - ./.docker/redis/redis.conf:/etc/redis/redis.conf:ro

volumes:
  rabbitmq_data:
  db_volume:
  redis_socket_cache:
  redis_socket_session:
  shop_volume:
    driver_opts:
      type: none
      o: bind
      device: ${WORKDIR}
  composer_cache:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/.composer

networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}